### ISSUE TITLE
Not working when request is the first loopback request

### ISSUE THREAD

**Issue by supermafete** [snowyu/loopback-component-current-user.js#1]
Hi there.

I'm experiencing an issue when I call an endpoint for the first time when loopback just run up. It does not recognize ctx.req.currentUser. After first call is made, then it's recognized correctly.

Just running up loopback, without any request made before
`curl http://localhost:3000/api/Customers/?access_token=oXoYeTHspQ8CUIrZImU1CfyibPixSMGUIg6M8LWv4VMJKGP93Wfjodt1Fpg8ebMK`

ctx.req.currentUser = undefined

Then, make another request:
`curl http://localhost:3000/api/Customers/?access_token=oXoYeTHspQ8CUIrZImU1CfyibPixSMGUIg6M8LWv4VMJKGP93Wfjodt1Fpg8ebMK`

ctx.req.currentUser = { MyUserData }

**Comment by snowyu** [comment]
Which Loopback version?

**Comment by supermafete** [comment]
3.11.1

**Comment by supermafete** [comment]
BTW, I made my own middleware and put it in "initial:after". Then it works well.

**Comment by snowyu** [comment]
did ensure that you enable the loopback#token middleware early in your `middleware.json` config?

```
{
  "initial:before": {
    "loopback#token": {}
  },
}
```

**Comment by supermafete** [comment]
Yes, it was in initial:before

**Comment by snowyu** [comment]
strange thing. I test it ok on loopback 3. Could you give me a simple demo to reproduce it?

**Comment by supermafete** [comment]
Hummm...

Tested with a fresh install and worked fine. Probably is a specific issue of my setup, sorry. Anyway I resolved it writing my own middleware.

Thanks!
